### ISSUE TITLE
Text files dont need to be zipped.

### ISSUE THREAD

**Issue by michaelgosling** [VivaNewVegas/Viva-New-Vegas-Patch-Emporium#1]
Stuff like loadorder.txt should really just be part of the repo as a txt, you're not gaining much if any compression from compressing it into a 7z archive.

**Comment by VivaNewVegas** [comment]
lol sorry for not responding for like over a month, i rarely check GitHub. But i find easier to open that zip from your browser and just dragging the .txt from there instead of going to the downloads folder and cutting pasting. matter of preference really, I don't think either is faster
