### ISSUE TITLE
YUP - JSawyer Patch.esp lowers hitpoints

### ISSUE THREAD

**Issue by MoerasGrizzly** [VivaNewVegas/Viva-New-Vegas-Patch-Emporium#1]
The YUP - JSawyer Patch lowers hitpoints beyond what JSawyer normally does and documents.

JSawyer HP formula: 50 + (End * 10) + ([Level - 1] * 5) - as per the readme
In FNV with only JSawyer.esp running, a Level 1, END1 character has 60 hitpoints
In FNV with JSawyer and YUP running, a level 1, END1 character has 60 hitpoints
In FNV with JSawyer, YUP and the patch running, said character has 10 hitpoints

This appears to be because the gamesetting fAVDHealthEnduranceOffset is set to -5 in the patch, with no such change existing in either YUP or JSawyer. The V5.1 changelog of the JSawyer mod mentions:
Game Settings:
* Removed dirty edits to fAVDHealthEnduranceOffset, fDiffMultXPVH , fDiffMultXPVE, fDiffMultXPH, fDiffMultXPE, fMagicMedicineSkillMult game settings.

Deleting the gamesetting from the patch restores the intended HP formula.

**Comment by VivaNewVegas** [comment]
fixed as of 1/03/20
