### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by danejasho** [VivaNewVegas/Viva-New-Vegas-Patch-Emporium#2]
I built my game out (TTW the best of times) from the date of 8/31/2020 on your change log. I haven't really played it yet, but I see that there's been a large number of updates since. Should I wipe and start over, and just try and piece through the changes as best I can?

**Comment by VivaNewVegas** [comment]
To be honest, non of the changes are 100% vital, so you could just roll with your current build. But if you do want to update, you should be able to just follow the changelog without needing to completely reinstall
