### ISSUE TITLE
Follower Formula Redone: Boone can be hired twice

### ISSUE THREAD

**Issue by Tea23** [VivaNewVegas/Viva-New-Vegas-Patch-Emporium#3]
Follower Formula Redone misses a check on `bBooneHired` in the dialogue option "Come with me, we can go after the Legion." and this means he can be "hired" twice. "Hiring" him the "second" time seems to take up a companion slot, as even after dismissing him you won't be able to go to Zion with Jed Masterson or enter Caesar's tent (using a Companion Dismissal Terminal helps this).

I have attached a patch for this. Please feel free to review it and merge it into the main ESP if you agree with this fix.
[ffr - Boone Hire Fix.zip](https://github.com/VivaNewVegas/Viva-New-Vegas-Patch-Emporium/files/6052838/ffr.-.Boone.Hire.Fix.zip)

For casual readers coming across this: If you use the above patch, make sure it is placed _after_ FFR in your load order.

**Comment by Tea23** [comment]
Did not see a fix was already committed!

**Comment by Tea23** [comment]
False alarm on closure; the current version of the patch _does not_ actually prevent this.

**Comment by Tea23** [comment]
[ffr - Boone Hire Fix2.zip](https://github.com/VivaNewVegas/Viva-New-Vegas-Patch-Emporium/files/6053130/ffr.-.Boone.Hire.Fix2.zip)

Cleaner version. Won't be detected as a conflict in xEdit and can be more effortlessly copied over to the original.

**Comment by VivaNewVegas** [comment]
Thanks! That bug got introduced after I fixed the opposite bug, being able to hire boon with insufficient charisma lol. I think I may actually upload this mod to Nexus now that everything *should* be fixed, so thanks. I'll def credit you on the Nexus page
