### ISSUE TITLE
lStewieAl's Tweaks Custom INI update suggestion for new version

### ISSUE THREAD

**Issue by davorvr** [VivaNewVegas/Viva-New-Vegas-Patch-Emporium#5]
Hello, the [custom INI](https://github.com/VivaNewVegas/Viva-New-Vegas-Patch-Emporium/blob/main/lStewieAl's%20Tweaks%20Custom%20INI.7z) uses `bPipboyAPCost`, and the changelog of the latest v6.70 of [lStewieAl's Tweaks](https://www.nexusmods.com/newvegas/mods/66347) lists a change of this variable's name to `iPipboyAPCost`.

I have decided to open up an issue instead of submitting a pull request because, for a small change such as this one, I figured it is likely easier for you guys to just update the file manually instead of inspecting a pull request for a blob. Thank you for your work on this guide/mod set!

EDIT: Misspelling of the mod name.

**Comment by VivaNewVegas** [comment]
Finally got around to updating the INI, thanks for pointing that out
