### ISSUE TITLE
Update loadorder.txt

### ISSUE THREAD

**Issue by NekoAlosama** [VivaNewVegas/Viva-New-Vegas-Patch-Emporium#7]
The current one is missing a few mods, so some mods that are in the guide aren't accounted for but are easily seen at the bottom of the load order
* Muzzle flash is in Tweaks
* Interior lighting is in Visuals
* Economy Overhaul is recommended as a replacement in Mods to Avoid.
![Screenshot_192](https://user-images.githubusercontent.com/47763383/141225282-261b3229-03f9-404a-b99f-172f6a451093.png)

**Comment by NekoAlosama** [comment]
@TDarkShadow @VivaNewVegas

**Comment by VivaNewVegas** [comment]
Late response, but those files have all had their ESPs removed in favor of JIP Script Runner files
